### ISSUE TITLE
Backend page route broken in 3.3

### ISSUE THREAD

**Issue by graham73may** [graham73may/bolt-taxonomy-editor#2]
`/bolt/extend/taxonomyeditor` needs to change to `/bolt/extensions/taxonomyeditor` for Bolt 3.4+

**Comment by navelpluisje** [comment]
isn't it 3.3+?

**Comment by graham73may** [comment]
Done some digging, looks like 3.3 yes. https://github.com/bolt/bolt/pull/6156

Will put out a release when 3.3 is released with the minimum bolt version defined.

**Comment by navelpluisje** [comment]
You can use `Bolt\Version as Version` and call `Version::compare('3.3', '>')`. If true version < 3.3

**Comment by graham73may** [comment]
3.3 Support added.
