### ISSUE TITLE
Bolt 3.3.1 route not found

### ISSUE THREAD

**Issue by simonmnt** [graham73may/bolt-taxonomy-editor#5]
I updated bolt, and the routing not match with the new version.

> Uncaught Exception: NotFoundHttpException .
        NotFoundHttpException in RouterListener.php line 176: 
         No route found for "GET /bolt/extensions/taxonomyeditor"

**Comment by graham73may** [comment]
Closing as duplicate of #2

Will get this resolved ASAP. Should be pretty quick fix, the extensions URL changed from 3.2 to 3.3 in Bolt...

**Comment by graham73may** [comment]
@simonmnt 3.3 support added. Please update to 0.3.1

**Comment by simonmnt** [comment]
I didn't see the issues, sorry. Thanks for the update.
